using NpgsqlTypes;
using System.ComponentModel.DataAnnotations;

namespace Library.CommonEnums
{
    public enum OrderSource
    {
        [PgName("direct_sales")]
        direct_sales,
        [PgName("sfa")]
        sfa
    }

    public enum ClaimApprovalStatus
    {
        [PgName("pending")]
        PENDING,
        [PgName("approved")]
        APPROVED,
        [PgName("rejected")]
        REJECTED,
        [PgName("handled_by_someone_else")]
        HANDLED_BY_SOMEONE_ELSE,
        [PgName("awaiting_at_other_level")]
        AWAITING_AT_OTHER_LEVEL,
        [PgName("pending_for_asm_approval")]
        PENDING_FOR_ASM_APPROVAL,
        [PgName("pending_for_rsm_approval")]
        PENDING_FOR_RSM_APPROVAL,
        [PgName("pending_for_zsm_approval")]
        PENDING_FOR_ZSM_APPROVAL,
        [PgName("pending_for_nsm_approval")]
        PENDING_FOR_NSM_APPROVAL,
        [PgName("pending_for_gsm_approval")]
        PENDING_FOR_GSM_APPROVAL,
        [PgName("pending_for_admin_approval")]
        PENDING_FOR_ADMIN_APPROVAL,
        [PgName("submitted_for_approval")]
        SUBMITTED_FOR_APPROVAL,
        [PgName("claim_cancelled")]
        CLAIM_CANCELLED,
        [PgName("cn_created")]
        CN_CREATED
    }

    public enum POOrderSource
    {
        [PgName("direct_sales")]
        direct_sales,
        [PgName("sfa")]
        sfa,
        [PgName("ars")]
        ars
    }

    public enum ClaimType
    {
        [PgName("custom")]
        custom,
        [PgName("return_claim")]
        return_claim,
        [PgName("scheme_claim")]
        scheme_claim,
        [PgName("margin_difference_claim")]
        margin_difference_claim,
        [PgName("master_claim")]
        master_claim
    }

    public enum EditingType
    {
        [Display(Name = "Retailer Level")]
        retailer_level = 0,
        [Display(Name = "Invoice Level")]
        invoice_level = 1
    }

    public enum OrderStatus
    {
        [PgName("edited")]
        EDITED,
        [PgName("pending_for_approval")]
        PENDING_FOR_APPROVAL,
        [PgName("in_progress")]
        IN_PROGRESS,
        [PgName("completed")]
        COMPLETED,
        [PgName("cancelled")]
        CANCELLED,
        [PgName("deleted")]
        DELETED,
        [PgName("pending")]
        PENDING,
        [PgName("not_delivered")]
        NOT_DELIVERED,
        [PgName("partially_delivered")]
        PARTIALLY_DELIVERED,
        [PgName("partially_collected")]
        PARTIALLY_COLLECTED,
        [PgName("partially_invoiced")]
        PARTIALLY_INVOICED,
        [PgName("invoiced")]
        INVOICED,
        [PgName("delivered")]
        DELIVERED,
        [PgName("approved")]
        APPROVED,
        [PgName("rejected")]
        REJECTED,
        [PgName("accepted")]
        ACCEPTED,
        [PgName("received")]
        RECEIVED,
        [PgName("audit_pending")]
        AUDIT_PENDING,
        [PgName("partially_audit")]
        PARTIALLY_AUDIT,
        [PgName("audit_done")]
        AUDIT_DONE,
        [PgName("pending_for_sap_cancellation")]
        PENDING_FOR_SAP_CANCELLATION,
        [PgName("so_created")]
        SO_CREATED,
        [PgName("pending_from_rh_approval")]
        PENDING_FROM_RH_APPROVAL,
        [PgName("approved_from_rh")]
        APPROVED_FROM_RH,
        [PgName("pending_from_logistics_approval")]
        PENDING_FROM_LOGISTICS_APPROVAL,
        [PgName("pending_from_finance_approval")]
        PENDING_FROM_FINANCE_APPROVAL,
        [PgName("pending_for_settlement")]
        PENDING_FOR_SETTLEMENT,
        [PgName("settled")]
        SETTLED,
        [PgName("pending_for_submission")]
        PENDING_FOR_SUBMISSION,
        [PgName("claim_created")]
        CLAIM_CREATED,
        [PgName("shipped")]
        SHIPPED,
        [PgName("closed")]
        CLOSED,
        [PgName("ready_to_dispatch")]
        READY_TO_DISPATCH
    }

    public enum POOrderStatus
    {
        [PgName("edited")]
        EDITED,
        [PgName("pending_for_approval")]
        PENDING_FOR_APPROVAL,
        [PgName("pending_for_asm_approval")]
        PENDING_FOR_ASM_APPROVAL,
        [PgName("pending_for_rsm_approval")]
        PENDING_FOR_RSM_APPROVAL,
        [PgName("pending_for_zsm_approval")]
        PENDING_FOR_ZSM_APPROVAL,
        [PgName("pending_for_nsm_approval")]
        PENDING_FOR_NSM_APPROVAL,
        [PgName("pending_for_gsm_approval")]
        PENDING_FOR_GSM_APPROVAL,
        [PgName("pending_for_admin_approval")]
        PENDING_FOR_ADMIN_APPROVAL,
        [PgName("in_progress")]
        IN_PROGRESS,
        [PgName("completed")]
        COMPLETED,
        [PgName("cancelled")]
        CANCELLED,
        [PgName("deleted")]
        DELETED,
        [PgName("pending")]
        PENDING,
        [PgName("not_delivered")]
        NOT_DELIVERED,
        [PgName("partially_delivered")]
        PARTIALLY_DELIVERED,
        [PgName("partially_collected")]
        PARTIALLY_COLLECTED,
        [PgName("partially_invoiced")]
        PARTIALLY_INVOICED,
        [PgName("invoiced")]
        INVOICED,
        [PgName("delivered")]
        DELIVERED,
        [PgName("approved")]
        APPROVED,
        [PgName("rejected")]
        REJECTED,
        [PgName("accepted")]
        ACCEPTED,
        [PgName("received")]
        RECEIVED,
        [PgName("audit_pending")]
        AUDIT_PENDING,
        [PgName("partially_audit")]
        PARTIALLY_AUDIT,
        [PgName("audit_done")]
        AUDIT_DONE,
        [PgName("pending_for_sap_cancellation")]
        PENDING_FOR_SAP_CANCELLATION,
        [PgName("so_created")]
        SO_CREATED,
        [PgName("pending_from_rh_approval")]
        PENDING_FROM_RH_APPROVAL,
        [PgName("approved_from_rh")]
        APPROVED_FROM_RH,
        [PgName("pending_from_logistics_approval")]
        PENDING_FROM_LOGISTICS_APPROVAL,
        [PgName("pending_from_finance_approval")]
        PENDING_FROM_FINANCE_APPROVAL,
        [PgName("pending_for_settlement")]
        PENDING_FOR_SETTLEMENT,
        [PgName("settled")]
        SETTLED,
        [PgName("pending_for_submission")]
        PENDING_FOR_SUBMISSION,
        [PgName("claim_created")]
        CLAIM_CREATED,
        [PgName("shipped")]
        SHIPPED,
        [PgName("closed")]
        CLOSED,
        [PgName("ready_to_dispatch")]
        READY_TO_DISPATCH,
        [PgName("pending_for_erp_approval")]
        PENDING_FOR_ERP_APPROVAL
    }

    public enum SOInvoiceStatus
    {
        [PgName("edited")]
        EDITED,
        [PgName("pending_for_approval")]
        PENDING_FOR_APPROVAL,
        [PgName("in_progress")]
        IN_PROGRESS,
        [PgName("completed")]
        COMPLETED,
        [PgName("cancelled")]
        CANCELLED,
        [PgName("deleted")]
        DELETED,
        [PgName("pending")]
        PENDING,
        [PgName("not_delivered")]
        NOT_DELIVERED,
        [PgName("partially_delivered")]
        PARTIALLY_DELIVERED,
        [PgName("partially_collected")]
        PARTIALLY_COLLECTED,
        [PgName("partially_invoiced")]
        PARTIALLY_INVOICED,
        [PgName("invoiced")]
        INVOICED,
        [PgName("delivered")]
        DELIVERED,
        [PgName("approved")]
        APPROVED,
        [PgName("rejected")]
        REJECTED,
        [PgName("accepted")]
        ACCEPTED,
        [PgName("received")]
        RECEIVED,
        [PgName("audit_pending")]
        AUDIT_PENDING,
        [PgName("partially_audit")]
        PARTIALLY_AUDIT,
        [PgName("audit_done")]
        AUDIT_DONE,
        [PgName("pending_for_sap_cancellation")]
        PENDING_FOR_SAP_CANCELLATION,
        [PgName("so_created")]
        SO_CREATED,
        [PgName("pending_from_rh_approval")]
        PENDING_FROM_RH_APPROVAL,
        [PgName("approved_from_rh")]
        APPROVED_FROM_RH,
        [PgName("pending_from_logistics_approval")]
        PENDING_FROM_LOGISTICS_APPROVAL,
        [PgName("pending_from_finance_approval")]
        PENDING_FROM_FINANCE_APPROVAL,
        [PgName("pending_for_settlement")]
        PENDING_FOR_SETTLEMENT,
        [PgName("settled")]
        SETTLED,
        [PgName("pending_for_submission")]
        PENDING_FOR_SUBMISSION,
        [PgName("claim_created")]
        CLAIM_CREATED,
        [PgName("shipped")]
        SHIPPED,
        [PgName("closed")]
        CLOSED,
        [PgName("ready_to_dispatch")]
        READY_TO_DISPATCH
    }

    public enum SODeliveryStatus
    {
        [PgName("edited")]
        EDITED,
        [PgName("pending_for_approval")]
        PENDING_FOR_APPROVAL,
        [PgName("in_progress")]
        IN_PROGRESS,
        [PgName("completed")]
        COMPLETED,
        [PgName("cancelled")]
        CANCELLED,
        [PgName("deleted")]
        DELETED,
        [PgName("pending")]
        PENDING,
        [PgName("not_delivered")]
        NOT_DELIVERED,
        [PgName("partially_delivered")]
        PARTIALLY_DELIVERED,
        [PgName("partially_collected")]
        PARTIALLY_COLLECTED,
        [PgName("partially_invoiced")]
        PARTIALLY_INVOICED,
        [PgName("invoiced")]
        INVOICED,
        [PgName("delivered")]
        DELIVERED,
        [PgName("approved")]
        APPROVED,
        [PgName("rejected")]
        REJECTED,
        [PgName("accepted")]
        ACCEPTED,
        [PgName("received")]
        RECEIVED,
        [PgName("audit_pending")]
        AUDIT_PENDING,
        [PgName("partially_audit")]
        PARTIALLY_AUDIT,
        [PgName("audit_done")]
        AUDIT_DONE,
        [PgName("pending_for_sap_cancellation")]
        PENDING_FOR_SAP_CANCELLATION,
        [PgName("so_created")]
        SO_CREATED,
        [PgName("pending_from_rh_approval")]
        PENDING_FROM_RH_APPROVAL,
        [PgName("approved_from_rh")]
        APPROVED_FROM_RH,
        [PgName("pending_from_logistics_approval")]
        PENDING_FROM_LOGISTICS_APPROVAL,
        [PgName("pending_from_finance_approval")]
        PENDING_FROM_FINANCE_APPROVAL,
        [PgName("pending_for_settlement")]
        PENDING_FOR_SETTLEMENT,
        [PgName("settled")]
        SETTLED,
        [PgName("pending_for_submission")]
        PENDING_FOR_SUBMISSION,
        [PgName("claim_created")]
        CLAIM_CREATED,
        [PgName("shipped")]
        SHIPPED,
        [PgName("closed")]
        CLOSED,
        [PgName("ready_to_dispatch")]
        READY_TO_DISPATCH
    }

    public enum OrderCategory
    {

        [PgName("return")]
        RETURN,
        [PgName("normal")]
        NORMAL
    }

    public enum PaymentStatus
    {
        [PgName("in_process")]
        IN_PROCESS,
        [PgName("pending")]
        PENDING,
        [PgName("done")]
        DONE
    }

    public enum POPaymentStatus
    {
        [PgName("in_process")]
        IN_PROCESS,
        [PgName("pending")]
        PENDING,
        [PgName("done")]
        DONE
    }

    public enum OrderType
    {
        [PgName("rush")]
        Rush,
        [PgName("normal")]
        Normal,
        [PgName("express")]
        Express
    }

    public enum SIOrderSource
    {
        [PgName("direct_sales")]
        direct_sales,
        [PgName("sfa")]
        sfa,
        [PgName("idt")]
        idt,
        [PgName("direct_sales_master")]
        direct_sales_master,
        [PgName("ars")]
        ars
    }
    public enum SIInvoiceType
    {
        [PgName("direct")]
        direct,
        [PgName("excel")]
        excel,
        [PgName("bulk_invoice")]
        bulk_invoice,
        [PgName("purchase_invoice")]
        purchase_invoice,
        [PgName("van_sales")]
        van_sales
    }

    public enum SIOrderStatus
    {
        [PgName("edited")]
        Edited,
        [PgName("pending_for_approval")]
        PENDING_FOR_APPROVAL,
        [PgName("in_progress")]
        IN_PROGRESS,
        [PgName("completed")]
        COMPLETED,
        [PgName("cancelled"), Display(Name = "cancelled")]
        CANCELLED,
        [PgName("deleted")]
        DELETED,
        [PgName("pending"), Display(Name = "pending")]
        PENDING,
        [PgName("not_delivered")]
        NOT_DELIVERED,
        [PgName("partially_delivered")]
        PARTIALLY_DELIVERED,
        [PgName("partially_collected")]
        PARTIALLY_COLLECTED,
        [PgName("partially_invoiced")]
        PARTIALLY_INVOICED,
        [PgName("invoiced")]
        INVOICED,
        [PgName("delivered")]
        DELIVERED,
        [PgName("approved")]
        APPROVED,
        [PgName("rejected")]
        REJECTED,
        [PgName("accepted")]
        ACCEPTED,
        [PgName("received")]
        RECEIVED,
        [PgName("audit_pending")]
        AUDIT_PENDING,
        [PgName("partially_audit")]
        PARTIALLY_AUDIT,
        [PgName("audit_done")]
        AUDIT_DONE,
        [PgName("pending_for_sap_cancellation")]
        PENDING_FOR_SAP_CANCELLATION,
        [PgName("so_created")]
        SO_CREATED,
        [PgName("pending_from_rh_approval")]
        PENDING_FROM_RH_APPROVAL,
        [PgName("approved_from_rh")]
        APPROVED_FROM_RH,
        [PgName("pending_from_logistics_approval")]
        PENDING_FROM_LOGISTICS_APPROVAL,
        [PgName("pending_from_finance_approval")]
        PENDING_FROM_FINANCE_APPROVAL,
        [PgName("pending_for_settlement")]
        PENDING_FOR_SETTLEMENT,
        [PgName("settled")]
        SETTLED,
        [PgName("pending_for_submission")]
        PENDING_FOR_SUBMISSION,
        [PgName("claim_created")]
        CLAIM_CREATED,
        [PgName("shipped")]
        SHIPPED,
        [PgName("closed")]
        CLOSED,
        [PgName("ready_to_dispatch")]
        READY_TO_DISPATCH
    }

    public enum SIEditStatus
    {
        [PgName("edited")]
        EDITED,
        [PgName("pending_for_approval")]
        PENDING_FOR_APPROVAL,
        [PgName("in_progress")]
        IN_PROGRESS,
        [PgName("completed")]
        COMPLETED,
        [PgName("cancelled")]
        CANCELLED,
        [PgName("deleted")]
        DELETED,
        [PgName("pending")]
        PENDING,
        [PgName("not_delivered")]
        NOT_DELIVERED,
        [PgName("partially_delivered")]
        PARTIALLY_DELIVERED,
        [PgName("partially_collected")]
        PARTIALLY_COLLECTED,
        [PgName("partially_invoiced")]
        PARTIALLY_INVOICED,
        [PgName("invoiced")]
        INVOICED,
        [PgName("delivered")]
        DELIVERED,
        [PgName("approved")]
        APPROVED,
        [PgName("rejected")]
        REJECTED,
        [PgName("accepted")]
        ACCEPTED,
        [PgName("received")]
        RECEIVED,
        [PgName("audit_pending")]
        AUDIT_PENDING,
        [PgName("partially_audit")]
        PARTIALLY_AUDIT,
        [PgName("audit_done")]
        AUDIT_DONE,
        [PgName("pending_for_sap_cancellation")]
        PENDING_FOR_SAP_CANCELLATION,
        [PgName("so_created")]
        SO_CREATED,
        [PgName("pending_from_rh_approval")]
        PENDING_FROM_RH_APPROVAL,
        [PgName("approved_from_rh")]
        APPROVED_FROM_RH,
        [PgName("pending_from_logistics_approval")]
        PENDING_FROM_LOGISTICS_APPROVAL,
        [PgName("pending_from_finance_approval")]
        PENDING_FROM_FINANCE_APPROVAL,
        [PgName("pending_for_settlement")]
        PENDING_FOR_SETTLEMENT,
        [PgName("settled")]
        SETTLED,
        [PgName("pending_for_submission")]
        PENDING_FOR_SUBMISSION,
        [PgName("claim_created")]
        CLAIM_CREATED,
        [PgName("shipped")]
        SHIPPED,
        [PgName("closed")]
        CLOSED,
        [PgName("ready_to_dispatch")]
        READY_TO_DISPATCH
    }

    public enum SRApprovalStatus
    {
        [PgName("pending")]
        Pending,
        [PgName("approved")]
        Approved,

        [PgName("rejected")]
        Rejected,
        [PgName("pending_for_asm_approval")]
        Pending_For_Asm_Approval,

        [PgName("pending_for_rsm_approval")]
        Pending_For_Rsm_Approval,
        [PgName("pending_for_nsm_approval")]
        Pending_For_Nsm_Approval,

        [PgName("pending_for_gsm_approval")]
        Pending_for_gsm_approval,
        [PgName("pending_for_zsm_approval")]
        Pending_for_zsm_approval,

        [PgName("pending_for_admin_approval")]
        pending_for_admin_approval,
        [PgName("cn_created")]
        cn_created,

        [PgName("handled_by_someone_else")]
        handled_by_someone_else,
        [PgName("awaiting_at_other_level")]
        awaiting_at_other_level,

        [PgName("submitted_for_approval")]
        submitted_for_approval,
    }

    public enum SRGoodReturnType
    {
        [PgName("primary")]
        primary,
        [PgName("secondary")]
        secondary,
    }

    public enum SROrderSource
    {
        [PgName("direct_sales")]
        direct_sales,
        [PgName("direct_sales_master")]
        direct_sales_master,
        [PgName("sfa")]
        sfa,

        [PgName("idt")]
        idt,
        [PgName("ars")]
        ars,
    }

    public enum SRReturnItemReason
    {
        [PgName("expired")]
        expired,
        [PgName("damaged")]
        damaged,
        [PgName("fresh_quantity")]
        fresh_quantity,
        [PgName("short_received")]
        short_received,
    }

    public enum SRReturnSource
    {
        [PgName("invoice")]
        invoice,
        [PgName("loose")]
        loose,
    }

    public enum SRReturnItemSource
    {
        [PgName("invoice")]
        invoice,
        [PgName("loose")]
        loose,
    }
}
