name: Test PR on main, develop
on:
  pull_request:
    branches: [main, develop]
concurrency:
  group: ${{ github.workflow }}-${{ github.event.pull_request.number || github.ref }}
  cancel-in-progress: true
jobs:
  build:
    name: 'Test PR for test cases and build'
    runs-on: self-hosted
    env:
      DOTNET_INSTALL_DIR: "./.dotnet"
    steps:
      - uses: actions/checkout@v3
        with:
          persist-credentials: false
          
      - name: Setup .NET SDK
        uses: actions/setup-dotnet@v3
        with:
          # Semantic version range syntax or exact version of a dotnet version
          dotnet-version: '7.0.x'

      - name: Install dependencies
        run: dotnet restore

      - name: Check code formatting
        run: dotnet format --verify-no-changes

      - name: Run tests
        run: dotnet test --filter TestCategory=main
      
      - name: Build solution
        id: build-image
        run: |
          docker build "$GITHUB_WORKSPACE" -f  "DmsSoSyncProcessor/Dockerfile"